---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{storagename}}
  labels:
    app: {{appname}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appname}}
  labels:
    app: {{appname}}
spec:
  selector:
    matchLabels:
      app: {{appname}}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{appname}}
        tier: mysql
    spec:
      containers:
      - image: {{image_name}}:{{mysql_version}}
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{MYSQL_ROOT_PASSWORD}}
          - name: MYSQL_USER
            value: {{MYSQL_USER}}
          - name: MYSQL_PASSWORD
            value: {{MYSQL_PASSWORD}}
          - name: MYSQL_DATABASE
            value: {{MYSQL_DATABASE}}
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{storagename}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{appname}}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{appname}}
    tier: mysql
  type: LoadBalancer
