name: Build, Push, and Deploy - DEV Env
on:
  push:
    branches:
      - main

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: CloudTruth Configure
        uses: cloudtruth/configure-action@v2.2.0
        with:
          apikey: ${{ secrets.CLOUDTRUTH_API_KEY }}
          project: wordpress 
          environment: default

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Short SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and Push 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest
