name: Configure and Deploy - DEV Env
on:
  push:
    branches:
      - main

jobs:
  cloudtruth_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: CloudTruth Configure
        uses: cloudtruth/configure-action@v2.2.0
        with:
          apikey: ${{ secrets.CLOUDTRUTH_API_KEY }}
          project: wordpress 
          environment: default

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./wordpress-deployment.yaml
          kubectl apply -f ./mysql-deployment.yaml
